# Your specific keys provided by SonarQube Cloud during setup
sonar.organization=azurerashiyadevsecops
sonar.projectKey=azurerashiyadevsecops_java-sample-project

# Source code path
sonar.sources=src/main/java
#sonar.tests=src/test/java

# Encoding
sonar.sourceEncoding=UTF-8
