name: CI/CD Pipeline to EKS (DevSecOps)

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: java-prod-cluster

jobs:
  build-and-analyze:
    name: Build, Secure & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Compile Application
      run: mvn clean compile

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Run Checkov on Kubernetes Manifests
      uses: bridgecrewio/checkov-action@master
      with:
        framework: kubernetes
        directory: k8s/
        output_format: cli
        skip_check: CKV_K8S_39,CKV_K8S_43
        soft_fail: false

    - name: Build Application JAR
      run: mvn clean package -DskipTests

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: java-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .


    - name: Run Trivy Vulnerability Scanner on Local Docker Image
      uses: aquasecurity/trivy-action@v0.35.0
      with:
        image-ref: '${{ steps.login-ecr.outputs.registry }}/java-app:${{ github.sha }}'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        severity: 'HIGH,CRITICAL'

    - name: Push Docker Image to ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: java-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "IMAGE=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/all-in-one.yaml
        kubectl set image deployment/java-app-deployment java-app=${{ env.IMAGE }}
        kubectl rollout status deployment/java-app-deployment
